export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_TICKETS = 'LOAD_TICKETS';
export const LOADING_TICKETS = 'LOADING_TICKETS';
export const LOAD_TICKETS_FAILED = 'LOAD_TICKETS_FAILED';

export const REMOVE_TICKET = 'REMOVE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const ADD_TICKET = 'ADD_TICKET';
export const SAVE_SEARCH_RESULTS = 'SAVE_SEARCH_RESULTS';
